

GET http://localhost:3000/Products/

###
GET http://localhost:3000/Products/view
###
POST http://localhost:3000/Products/add
Content-Type: application/json

{
    "Name": "Submarine",
    "Phase": "Manufacturing",
    "PhaseFS": "none"
}
###
PATCH http://localhost:3000/Products/update/613723cdd18ec03e382e0216
Content-Type: application/json

{
    "ProductName": "Shammah",
    "ProductPhase": "Male",
    "PhaseFailed": "Soccer"
}
###
DELETE  http://localhost:3000/Products/delete/613723cdd18ec03e382e0216
